# Generated by Django 5.0.1 on 2024-01-06 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_setores_veiculo_odometro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horariosolicitado', models.DateTimeField(verbose_name='Data solicitação')),
                ('dataatendimento', models.DateField(blank=True, verbose_name='Atendido em')),
                ('dataagendamento', models.DateField(verbose_name='Agendado para')),
                ('servidor', models.CharField(max_length=100, verbose_name='Servidor')),
                ('tiposolicitacao', models.CharField(choices=[('E', 'EXTERNA'), ('I', 'INTERNA')], max_length=1, verbose_name='Solicitacao')),
                ('retorno', models.DateTimeField(blank=True, verbose_name='Retorno')),
                ('itinerario', models.TextField(max_length=500, verbose_name='Itinerário')),
                ('kminicial', models.IntegerField(blank=True, verbose_name='Km Saída')),
                ('kmfinal', models.IntegerField(blank=True, verbose_name='Km chegada')),
                ('observacoes', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
                ('motorista', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.motorista', verbose_name='Motorista')),
                ('veiculo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.veiculo', verbose_name='Veiculo')),
            ],
        ),
    ]
