# Generated by Django 5.0.1 on 2024-01-08 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_setores_veiculo_odometro'),
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagens',
            name='setor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.setores', verbose_name='Setor'),
        ),
    ]
