# Generated by Django 5.0.1 on 2024-01-09 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_setores_veiculo_odometro'),
        ('viagens', '0002_viagens_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagens',
            name='dataatendimento',
            field=models.DateField(blank=True, verbose_name='Atendido em'),
        ),
        migrations.AlterField(
            model_name='viagens',
            name='kmfinal',
            field=models.IntegerField(blank=True, verbose_name='Km chegada'),
        ),
        migrations.AlterField(
            model_name='viagens',
            name='kminicial',
            field=models.IntegerField(blank=True, verbose_name='Km Saída'),
        ),
        migrations.AlterField(
            model_name='viagens',
            name='motorista',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.motorista', verbose_name='Motorista'),
        ),
        migrations.AlterField(
            model_name='viagens',
            name='observacoes',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='viagens',
            name='retorno',
            field=models.DateTimeField(blank=True, verbose_name='Retorno'),
        ),
        migrations.AlterField(
            model_name='viagens',
            name='tiposolicitacao',
            field=models.CharField(choices=[('E', 'EXTERNA'), ('I', 'INTERNA')], max_length=1, verbose_name='Tipo Solicitacao'),
        ),
        migrations.AlterField(
            model_name='viagens',
            name='veiculo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.veiculo', verbose_name='Veiculo'),
        ),
    ]
